# Generated by Django 4.0.4 on 2022-05-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=55)),
                ("last_name", models.CharField(max_length=55)),
                ("email", models.EmailField(max_length=254)),
                ("prefix", models.CharField(max_length=10)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="govcontract.jobtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sub_title", models.CharField(max_length=255)),
                ("sub_gate", models.IntegerField()),
                ("palt_plan", models.FloatField()),
                ("bus_days", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IC", "Incomplete"),
                            ("IP", "In Progress"),
                            ("CP", "Complete"),
                        ],
                        default="IC",
                        max_length=2,
                    ),
                ),
                ("ssp_date", models.DateField()),
                ("comments", models.CharField(max_length=500)),
                (
                    "poc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="govcontract.teammember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sub_title", models.CharField(max_length=255)),
                ("gate", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IC", "Incomplete"),
                            ("IP", "In Progress"),
                            ("CP", "Complete"),
                        ],
                        default="IC",
                        max_length=2,
                    ),
                ),
                ("ssp_date", models.DateField()),
                ("comments", models.CharField(max_length=500)),
                ("items", models.ManyToManyField(to="govcontract.taskitem")),
            ],
        ),
    ]
