# Generated by Django 4.0.4 on 2022-06-16 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('sub_title', models.CharField(max_length=255, null=True)),
                ('slug', models.CharField(max_length=15, null=True)),
                ('type', models.CharField(max_length=55, null=True)),
                ('ucid', models.CharField(max_length=55, null=True)),
                ('status', models.CharField(choices=[('IC', 'Incomplete'), ('IP', 'In Progress'), ('CP', 'Complete')], default='IC', max_length=2)),
                ('pop_date', models.DateField(null=True)),
                ('g_o_p', models.IntegerField(null=True)),
                ('g_t_p', models.IntegerField(null=True)),
                ('g_tr_p', models.IntegerField(null=True)),
                ('g_fr_o_p', models.IntegerField(null=True)),
                ('g_fr_t_p', models.IntegerField(null=True)),
                ('g_fr_tr_p', models.IntegerField(null=True)),
                ('g_fr_fr_p', models.IntegerField(null=True)),
                ('g_fr_fv_p', models.IntegerField(null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, null=True)),
                ('last_name', models.CharField(max_length=55, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('prefix', models.CharField(max_length=10, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='items',
        ),
        migrations.AddField(
            model_name='task',
            name='bus_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='palt_plan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_gate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.ManyToManyField(to='govcontract.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='gate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ssp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='pointofcontact',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govcontract.position'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pocs',
            field=models.ManyToManyField(to='govcontract.pointofcontact'),
        ),
        migrations.AddField(
            model_name='task',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govcontract.contract'),
        ),
        migrations.AddField(
            model_name='task',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govcontract.pointofcontact'),
        ),
    ]
