# Generated by Django 4.0.4 on 2022-06-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0002_contract_pointofcontact_position_remove_taskitem_poc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='admin_buyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_pco',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='award_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cycle_code',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='need_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='pco',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ss_leads',
            field=models.ManyToManyField(related_name='ss_leads', to='govcontract.pointofcontact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pocs',
            field=models.ManyToManyField(related_name='pocs', to='govcontract.pointofcontact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
