# Generated by Django 4.0.4 on 2022-06-17 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0003_contract_admin_buyer_contract_admin_pco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='admin_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_buyer', to='govcontract.position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='admin_pco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_pco', to='govcontract.position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='govcontract.position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='cycle_code',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_fr_fr_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_fr_fv_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_fr_o_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_fr_t_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_fr_tr_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_o_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_t_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='g_tr_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pco', to='govcontract.position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ucid',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='first_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='last_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govcontract.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govcontract.contract'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='gate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='palt_plan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
