# Generated by Django 4.0.4 on 2022-06-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0004_alter_contract_admin_buyer_alter_contract_admin_pco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='admin_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_buyer', to='govcontract.pointofcontact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='admin_pco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_pco', to='govcontract.pointofcontact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='govcontract.pointofcontact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pco', to='govcontract.pointofcontact'),
        ),
    ]
