# Generated by Django 4.0.4 on 2022-06-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0005_alter_contract_admin_buyer_alter_contract_admin_pco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='award_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='need_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pop_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='ssp_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
