# Generated by Django 4.0.4 on 2022-06-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0006_alter_contract_award_date_alter_contract_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='poc_ids',
            field=models.ManyToManyField(related_name='poc_ids', to='govcontract.pointofcontact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ss_lead_ids',
            field=models.ManyToManyField(related_name='ss_lead_ids', to='govcontract.pointofcontact'),
        ),
    ]
