# Generated by Django 4.0.4 on 2022-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0008_remove_contract_pocs_remove_contract_ss_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='poc_ids',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ss_lead_ids',
        ),
        migrations.AddField(
            model_name='contract',
            name='pocs',
            field=models.ManyToManyField(related_name='pocs', to='govcontract.pointofcontact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ss_leads',
            field=models.ManyToManyField(related_name='ss_leads', to='govcontract.pointofcontact'),
        ),
    ]
