# Generated by Django 4.0.4 on 2022-06-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0009_remove_contract_poc_ids_remove_contract_ss_lead_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id', to='govcontract.contract'),
        ),
        migrations.AlterField(
            model_name='task',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poc', to='govcontract.pointofcontact'),
        ),
    ]
