# Generated by Django 4.0.4 on 2022-06-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0010_alter_task_contract_id_alter_task_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='govcontract.task'),
        ),
    ]
