# Generated by Django 4.0.4 on 2022-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0011_remove_task_tasks_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.ManyToManyField(to='govcontract.task'),
        ),
    ]
