# Generated by Django 4.0.4 on 2022-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0012_task_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.ManyToManyField(null=True, to='govcontract.task'),
        ),
    ]
