# Generated by Django 4.0.4 on 2022-06-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0013_alter_task_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
    ]
