# Generated by Django 4.0.4 on 2022-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0014_remove_task_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
