# Generated by Django 4.0.4 on 2022-06-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0016_alter_pointofcontact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofcontact',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govcontract.position'),
        ),
    ]
