# Generated by Django 4.0.4 on 2022-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0017_alter_pointofcontact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bus_days',
            field=models.FloatField(null=True),
        ),
    ]
