# Generated by Django 4.0.4 on 2022-06-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0019_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
