# Generated by Django 4.0.4 on 2022-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0020_alter_holiday_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
