# Generated by Django 4.0.4 on 2022-06-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0021_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
