# Generated by Django 4.0.4 on 2022-06-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0022_remove_task_completed_task_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pointofcontact',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='task',
            name='palt_actual',
            field=models.IntegerField(null=True),
        ),
    ]
