# Generated by Django 4.0.4 on 2022-06-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0023_alter_contract_options_alter_holiday_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='palt_actual',
            new_name='palt_act',
        ),
    ]
