# Generated by Django 4.0.4 on 2022-06-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0024_rename_palt_actual_task_palt_act'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='palt_act',
            new_name='palt_actual',
        ),
    ]
