# Generated by Django 4.0.4 on 2022-06-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0025_rename_palt_act_task_palt_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='palt_actual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
