# Generated by Django 4.0.4 on 2022-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0028_alter_holiday_date_alter_holiday_observed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='award_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='need_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pop_date',
            field=models.DateField(null=True),
        ),
    ]
