# Generated by Django 4.0.4 on 2022-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0029_alter_contract_award_date_alter_contract_need_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
