# Generated by Django 4.0.4 on 2022-07-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0032_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
