# Generated by Django 4.0.4 on 2022-07-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0033_alter_template_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='subtitle',
            new_name='sub_title',
        ),
    ]
