# Generated by Django 4.0.4 on 2022-07-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0034_rename_subtitle_template_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('meta', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
