# Generated by Django 4.0.4 on 2022-07-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0036_task_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='links',
        ),
        migrations.AddField(
            model_name='task',
            name='links',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
