# Generated by Django 4.0.4 on 2022-07-17 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0037_remove_task_links_task_links_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
