# Generated by Django 4.0.4 on 2022-07-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0038_alter_task_status_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='caa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caa', to='govcontract.pointofcontact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdo', to='govcontract.pointofcontact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='ssa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ssa', to='govcontract.pointofcontact'),
            preserve_default=False,
        ),
    ]
