# Generated by Django 4.0.4 on 2022-07-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govcontract', '0039_contract_caa_contract_sdo_contract_ssa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comments',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sub_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ucid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='details',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pointofcontact',
            name='prefix',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='template',
            name='sub_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
